[project]
name = "compendium"
version = "0.1.0"
description = "A compendium of knowledge required in todays world of computer science."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material>=9.6.7",
]
